// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab1_bochkova.Data;

#nullable disable

namespace lab1_bochkova.Migrations
{
    [DbContext(typeof(BarbershopContext))]
    [Migration("20241022170732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lab1_bochkova.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarberId = 1,
                            CustomerId = 1,
                            EndTime = new DateTime(2024, 10, 20, 17, 30, 0, 0, DateTimeKind.Local),
                            ServiceId = 1,
                            StartTime = new DateTime(2024, 10, 20, 17, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            BarberId = 2,
                            CustomerId = 2,
                            EndTime = new DateTime(2024, 10, 20, 20, 0, 0, 0, DateTimeKind.Local),
                            ServiceId = 2,
                            StartTime = new DateTime(2024, 10, 20, 19, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("lab1_bochkova.Models.Barber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperienceLevel = 5,
                            Name = "Иван Иванов"
                        },
                        new
                        {
                            Id = 2,
                            ExperienceLevel = 3,
                            Name = "Петр Петров"
                        });
                });

            modelBuilder.Entity("lab1_bochkova.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Алексей Смирнов",
                            PreferredStyle = "Классический"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Максим Сидоров",
                            PreferredStyle = "Модерн"
                        });
                });

            modelBuilder.Entity("lab1_bochkova.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 30,
                            Name = "Стрижка машинкой",
                            Price = 1000
                        },
                        new
                        {
                            Id = 2,
                            Duration = 60,
                            Name = "Стрижка ножницами",
                            Price = 1500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
